language: node_js
node_js:
  - "8"
script:
  - echo "Deploying..."
install:
 - npm install -g firebase-tools
after_success:
 - ng build --prod=true --outputPath=public
 - firebase deploy --token $FIREBASE_TOKEN